spring:
  datasource:
    url: jdbc:mysql://192.168.85.123:3306/local_test?useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

#mybatis-plus:
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mybatis.plus.entity
logging:
  level:
    com.mybatis.plus: debug